/// <reference lib="webworker" />

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { type PrecacheEntry, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
	CacheFirst,
	NetworkFirst,
	StaleWhileRevalidate,
} from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope & {
	__WB_MANIFEST: Array<PrecacheEntry | string>;
};

// Take control of all pages as soon as the service worker is activated
clientsClaim();

// Precache all assets generated by the build process
// This will be automatically populated by workbox during build
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts with a CacheFirst strategy
registerRoute(
	({ url }: { url: URL }) =>
		url.origin === "https://fonts.googleapis.com" ||
		url.origin === "https://fonts.gstatic.com",
	new CacheFirst({
		cacheName: "google-fonts",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 30,
				maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
			}),
		],
	}),
);

// Cache images with a CacheFirst strategy
registerRoute(
	({ request }: { request: Request }) => request.destination === "image",
	new CacheFirst({
		cacheName: "images",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 60,
				maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
			}),
		],
	}),
);

// Cache CSS and JS files with a StaleWhileRevalidate strategy
registerRoute(
	({ request }: { request: Request }) =>
		request.destination === "style" || request.destination === "script",
	new StaleWhileRevalidate({
		cacheName: "static-resources",
	}),
);

// Cache VietQR API responses with NetworkFirst strategy
// Falls back to cache if network is unavailable
registerRoute(
	({ url }: { url: URL }) => url.origin === "https://api.vietqr.io",
	new NetworkFirst({
		cacheName: "vietqr-api",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 60 * 60 * 24, // 1 day
			}),
		],
		networkTimeoutSeconds: 5, // Fallback to cache if network takes too long
	}),
);

// Cache navigation requests (HTML) with NetworkFirst
registerRoute(
	({ request }: { request: Request }) => request.mode === "navigate",
	new NetworkFirst({
		cacheName: "pages",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 10,
				maxAgeSeconds: 60 * 60 * 24 * 7, // 1 week
			}),
		],
	}),
);

// Listen for skip waiting message
self.addEventListener("message", (event) => {
	if (event.data && event.data.type === "SKIP_WAITING") {
		self.skipWaiting();
	}
});

// Clean up old caches on activation
self.addEventListener("activate", (event) => {
	const cacheWhitelist = [
		"google-fonts",
		"images",
		"static-resources",
		"vietqr-api",
		"pages",
	];

	event.waitUntil(
		caches.keys().then((cacheNames) => {
			return Promise.all(
				cacheNames.map((cacheName) => {
					if (
						!cacheWhitelist.includes(cacheName) &&
						!cacheName.startsWith("workbox-precache")
					) {
						console.log("Deleting old cache:", cacheName);
						return caches.delete(cacheName);
					}
					return Promise.resolve();
				}),
			);
		}),
	);
});

console.log("Service Worker loaded with Workbox caching strategies!");
